name: Build dist.zip (Vite)
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Add .htaccess for SPA
        run: |
          cat > dist/.htaccess << 'EOF'
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
          EOF

      - name: Zip dist
        run: |
          cd dist
          zip -r ../dist.zip .
          cd ..

      - name: Upload artifact (dist.zip)
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist.zip
          retention-days: 7
